### ISSUE TITLE
Legacy Spigot is not supported

### ISSUE THREAD

**Issue by amadeusmz** [ScreamingSandals/ScreamingLib#6]
[17:22:21 ERROR]: [org.bukkit.craftbukkit.v1_12_R1.CraftServer] org/bukkit/block/data/BlockData initializing BedWars v0.3.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/block/data/BlockData
        at org.screamingsandals.bedwars.lib.bukkit.world.BukkitBlockMapper.<init>(BukkitBlockMapper.java:37) ~[?:?]
        at org.screamingsandals.bedwars.lib.world.BlockMapper.init(BlockMapper.java:51) ~[?:?]
        at org.screamingsandals.bedwars.lib.bukkit.world.BukkitBlockMapper.init(BukkitBlockMapper.java:24) ~[?:?]
        at org.screamingsandals.bedwars.Main_BukkitImpl.onLoad(Main_BukkitImpl.java:204) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[GoldenStar-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[GoldenStar-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[GoldenStar-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.BlockData
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[GoldenStar-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[GoldenStar-1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 8 more

**Comment by Misat11** [comment]
Current snapshots are unsafe to use, we have not started testing on legacy versions yet.
